### ISSUE TITLE
Any plans on adding golang-support?

### ISSUE THREAD

**Issue by EugenMayer** [elementsweb/generator-concourse-resource#1]
first, thank you for the generator, very helpful!

Are there any plans to add golang support or is that rather out of scope?

**Comment by elementsweb** [comment]
Hi @EugenMayer,

I've not got any experience using golang so don't know how to write the example scripts like I've done for shell and python. If you'd like to contribute though, if you provide an `out` script just like https://github.com/elementsweb/generator-concourse-resource/blob/master/generators/app/templates/scripts/python/out but for golang, I'd be happy to take care of integrating it with the generator.

**Comment by EugenMayer** [comment]
@elementsweb cool, i just started off an "reference app" https://github.com/EugenMayer/concourse-static-resource here trying to adopt the best practises. I yet miss unit testing and probably doing a bit of hand-made integration tests. But those tests are basically important to any concourse resource. I keep you posted, thanks for having interest!
